### ISSUE TITLE
Ping url parseing issue

### ISSUE THREAD

**Issue by Criten** [djberg96/net-ping#51]
https://github.com/djberg96/net-ping/blob/master/lib/net/ping/http.rb#L82

Net::Ping::HTTP.ping should check for http at the beginning of the string, not anywhere inside of the string.

Ex.
```
irb(main):004:0> host = "url_with_http.com"
=> "url_with_http.com"
irb(main):005:0> host = "http://#{host}" unless host.include?("http")
=> nil
irb(main):006:0> host
=> "url_with_http.com"
```

What we should get is

```
=> "http://url_with_http.com"
```

===
Proposed solution

```
host = "http://#{host}" unless /\A(http(s)?:\/\/)/.match(host)
```

**Comment by djberg96** [comment]
I am no longer the maintainer of this gem. Please post at https://github.com/chernesk/net-ping.

**Comment by Criten** [comment]
Oops! I actually meant to post it there.. not sure how it made it back here ;)

**Comment by djberg96** [comment]
NP. I'll go ahead and close this.
