### ISSUE TITLE
More relevant duration

### ISSUE THREAD

**Issue by Qwertyn** [djberg96/net-ping#52]
If end_time calculate a little earlier, the duration would be more relevant.
```ruby
# lib/net/ping/external.rb
...
Open3.popen3(*pcmd) do |stdin, stdout, stderr, thread|
  stdin.close
  @end_time = Time.now # <-------
  err = stderr.gets # Can't chomp yet, might be nil
...
# There is no duration if the ping failed
@duration = @end_time - start_time if bool
...
```
What it can be fraught with?
(What negative consequences can be?)

**Comment by djberg96** [comment]
@Qwertyn I no longer maintain this gem. Please post over at https://github.com/chernesk/net-ping.

**Comment by chernesk** [comment]
@Qwertyn I didn't have issues open. Can you repost on my repo? Thanks!

**Comment by Qwertyn** [comment]
ok
